---

- name: Configure ufw for Debian flavored systems
  ansible.builtin.include_tasks: configure_ufw.yml
  when: ( ansible_facts['os_family'] == "Debian" and potos_firewall_force_type | string == 'none') or
        ( potos_firewall_force_type | string == "ufw")
