---

- name: Prepare
  hosts: all
  gather_facts: yes

  tasks:
    # Update the apt cache as it's potentialy outdated in the container
    - name: update apt
      ansible.builtin.shell:  # noqa: command-instead-of-module
        cmd: 'apt-get -qq update && apt-get -qq upgrade -y && apt-get -y install apt-utils && apt-get -y install -qq -o=Dpkg::Use-Pty=0 iptables'
      when: ansible_distribution == 'Ubuntu'
      register: out
      changed_when: "'0 upgraded' not in out.stdout"

    - name: enable ip6tables
      ansible.builtin.shell:  # noqa: command-instead-of-shell
        cmd: 'update-alternatives --set ip6tables /usr/sbin/ip6tables-nft'
      changed_when: false
