---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
    - name: check if ufw rule has been configured
      ansible.builtin.command: ufw status verbose
      register: out
      changed_when: false
      failed_when: out is not search("124/tcp                    ALLOW IN    123.123.123.123")
